In [1]:
import pandas as pd
import numpy as np


# Load Data

train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")
features = pd.read_csv("../data/features.csv")
stores = pd.read_csv("../data/stores.csv")

train.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [8]:
test.head()

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [9]:
stores.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [4]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [13]:
data = train.merge(features, on=["Store", "Date", "IsHoliday"], how="left")
data = data.merge(stores, on="Store", how="left")

# Fill Missing Values

markdown_cols = ["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"]

data[markdown_cols] = data[markdown_cols].fillna(0)

# Date Feature 

data["Date"] = pd.to_datetime(data["Date"])
data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data["Day"] = data["Date"].dt.day
data = data.sort_values("Date").reset_index(drop=True)

print("Data loaded successfully!")
print(data.shape)

data.to_csv("../data/processed_data.csv", index=False)

Data loaded successfully!
(421570, 19)

In [14]:
data.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Year,Month,Day
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315,2010,2,5
1,29,5,2010-02-05,15552.08,False,24.36,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,10.064,B,93638,2010,2,5
2,29,6,2010-02-05,3200.22,False,24.36,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,10.064,B,93638,2010,2,5
3,29,7,2010-02-05,10820.05,False,24.36,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,10.064,B,93638,2010,2,5
4,29,8,2010-02-05,20055.64,False,24.36,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,10.064,B,93638,2010,2,5

In [15]:
data.tail()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Year,Month,Day
421565,40,87,2012-10-26,24638.96,False,49.65,3.917,3605.71,55.98,0.28,486.81,1389.06,138.728161,4.145,A,155083,2012,10,26
421566,19,30,2012-10-26,3740.12,False,56.49,4.071,5430.75,90.07,0.00,904.34,1665.77,138.728161,7.992,A,203819,2012,10,26
421567,19,31,2012-10-26,3128.17,False,56.49,4.071,5430.75,90.07,0.00,904.34,1665.77,138.728161,7.992,A,203819,2012,10,26
421568,19,33,2012-10-26,5740.14,False,56.49,4.071,5430.75,90.07,0.00,904.34,1665.77,138.728161,7.992,A,203819,2012,10,26
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,B,118221,2012,10,26